name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        jdk:
          - temurin@8
          - temurin@21
        os:
          - ubuntu-latest
          - windows-latest
          - macos-14
        scala:
          - 2.13
          - 3
        include:
          - scala: '2.13'
            scala-version: 2.13.16
          - scala: '3'
            scala-version: 3.6.4
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Ignore line ending differences in git
        if: contains(runner.os, 'windows')
        shell: bash
        run: git config --global core.autocrlf false

      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Setup sbt
        uses: sbt/setup-sbt@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Check formatting
        run: sbt "++${{ matrix.scala-version }} scalafmtCheckAll" scalafmtSbtCheck

      - name: Run linter
        run: sbt "++${{ matrix.scala-version }} scalafixCheckAll"

      - name: Compile
        run: sbt "++${{ matrix.scala-version }} compile"

      - name: Run tests
        shell: bash
        run: >
          if [[ "${{ matrix.scala }}" =~ ^2\..* ]]; then
            sbt coverage "++${{ matrix.scala-version }} test";
            else
            sbt "++${{ matrix.scala-version }} test";
            fi

      - name: Upload coverage data to Coveralls
        if: startsWith(matrix.scala, '2')
        run: sbt ++${{ matrix.scala-version }} coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala-version }}

      - name: Check mdoc output
        if: matrix.scala == '2.13'
        run: >
          sbt ++${{ matrix.scala-version }} mdoc &&
          git diff --exit-code
